POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: shivam
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: sql_demo


#Server
SERVER_PORT: 7000
ACTIVE_PROFILE: test

#Email Config
EMAIL_HOST: smtp.hostinger.com
EMAIL_PORT: 587
EMAIL_ID: support@vbspu.site
EMAIL_PASSWORD: Iti@2323
VERIFY_EMAIL_HOST: https://localhost:${SERVER_PORT}