POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: shivam
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: sql_demo


#Server
SERVER_PORT: 7000
ACTIVE_PROFILE: test

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL ADDRESS>
EMAIL_PASSWORD: <YOUR PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}