#Database
POSTGRES_SQL_USERNAME: u348475756_mailapi
POSTGRES_SQL_PASSWORD: Itisha@08
POSTGRES_SQL_HOST: 82.180.143.1
POSTGRES_SQL_PORT: 3306
POSTGRES_SQL_DB: u348475756_springmailapi


#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.hostinger.com
EMAIL_PORT: 587
EMAIL_ID: support@lovelymobilecenter.store
EMAIL_PASSWORD: Itisha@2550
VERIFY_EMAIL_HOST: https://localhost:${SERVER_PORT}